name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  NX_NON_INTERACTIVE: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Approve build scripts non-interactively (Prisma, etc.)
      - name: Approve build scripts
        run: yes | pnpm approve-builds

      # Generate Prisma client if schema exists (no DB needed)
      - name: Generate Prisma client
        if: ${{ hashFiles('prisma/schema.prisma') != '' }}
        env:
          # Dummy URL is fine for generate; no DB connection happens
          DATABASE_URL: "postgresql://user:pass@localhost:5432/db?schema=public"
        run: pnpm exec prisma generate

      # Compute base/head for PRs only; fallback to run-many on pushes (first commit safe)
      - name: Lint (affected on PR, run-many on push)
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.event.pull_request.head.sha }}"
            pnpm nx affected -t lint --base="$BASE" --head="$HEAD" --parallel=3
          else
            pnpm nx run-many -t lint --parallel=3
          fi

      - name: Prettier check
        run: pnpm format:check

      - name: Typecheck (no emit)
        run: pnpm typecheck
